/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'revoked' : IDL.Null,
});
export const Subscription = IDL.Record({
  'startTime' : Time,
  'status' : SubscriptionStatus,
  'principal' : IDL.Principal,
  'usedStorageBytes' : IDL.Nat,
  'endTime' : Time,
  'planId' : IDL.Nat,
  'storageLimitBytes' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Plan = IDL.Record({
  'active' : IDL.Bool,
  'planId' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'priceE8s' : IDL.Nat,
  'storageLimitBytes' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SubscribedUserEntry = IDL.Record({
  'startTime' : Time,
  'status' : SubscriptionStatus,
  'principal' : IDL.Principal,
  'endTime' : Time,
  'planId' : IDL.Nat,
  'storageLimitBytes' : IDL.Nat,
});
export const FileMetadata = IDL.Record({
  'contentType' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileId' : IDL.Nat,
  'folderId' : IDL.Opt(IDL.Nat),
  'uploadTime' : Time,
});
export const FolderRecord = IDL.Record({
  'ownerPrincipal' : IDL.Principal,
  'createTime' : Time,
  'folderName' : IDL.Text,
  'folderId' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateSubscription' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'adminDeleteFile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminDeleteUserFiles' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteUserSubscription' : IDL.Func([IDL.Principal], [], []),
  'adminListUsers' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'adminRevokeSubscription' : IDL.Func([IDL.Principal], [], []),
  'adminSetSubscription' : IDL.Func(
      [IDL.Principal, IDL.Nat, Time, Time, SubscriptionStatus],
      [IDL.Bool],
      [],
    ),
  'adminViewUserInfos' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Principal,
            IDL.Text,
            IDL.Nat,
            IDL.Nat,
            IDL.Text,
            IDL.Text,
          )
        ),
      ],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkHasActiveSubscription' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'confirmExtendSubscription' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createFolder' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createPlan' : IDL.Func([Plan], [IDL.Bool], []),
  'deleteFile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteFolder' : IDL.Func([IDL.Nat], [], []),
  'deletePlan' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'downloadFile' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAllUsersWithSubscriptionStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExtensionDetails' : IDL.Func([IDL.Nat], [IDL.Text, IDL.Nat], ['query']),
  'getPaymentDestination' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPlan' : IDL.Func([IDL.Nat], [IDL.Opt(Plan)], ['query']),
  'getPurchaseDetails' : IDL.Func([IDL.Nat], [IDL.Text, IDL.Nat], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscribedUsers' : IDL.Func(
      [],
      [IDL.Vec(SubscribedUserEntry)],
      ['query'],
    ),
  'getSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'listFilesInFolder' : IDL.Func([IDL.Nat], [IDL.Vec(FileMetadata)], ['query']),
  'listPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'listUserFolders' : IDL.Func([], [IDL.Vec(FolderRecord)], ['query']),
  'purchaseSubscription' : IDL.Func([IDL.Nat], [IDL.Text, IDL.Nat], ['query']),
  'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'setPaymentDestination' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePlan' : IDL.Func([Plan], [IDL.Bool], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Nat), IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'revoked' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'startTime' : Time,
    'status' : SubscriptionStatus,
    'principal' : IDL.Principal,
    'usedStorageBytes' : IDL.Nat,
    'endTime' : Time,
    'planId' : IDL.Nat,
    'storageLimitBytes' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Plan = IDL.Record({
    'active' : IDL.Bool,
    'planId' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'priceE8s' : IDL.Nat,
    'storageLimitBytes' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SubscribedUserEntry = IDL.Record({
    'startTime' : Time,
    'status' : SubscriptionStatus,
    'principal' : IDL.Principal,
    'endTime' : Time,
    'planId' : IDL.Nat,
    'storageLimitBytes' : IDL.Nat,
  });
  const FileMetadata = IDL.Record({
    'contentType' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileId' : IDL.Nat,
    'folderId' : IDL.Opt(IDL.Nat),
    'uploadTime' : Time,
  });
  const FolderRecord = IDL.Record({
    'ownerPrincipal' : IDL.Principal,
    'createTime' : Time,
    'folderName' : IDL.Text,
    'folderId' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateSubscription' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'adminDeleteFile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminDeleteUserFiles' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteUserSubscription' : IDL.Func([IDL.Principal], [], []),
    'adminListUsers' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'adminRevokeSubscription' : IDL.Func([IDL.Principal], [], []),
    'adminSetSubscription' : IDL.Func(
        [IDL.Principal, IDL.Nat, Time, Time, SubscriptionStatus],
        [IDL.Bool],
        [],
      ),
    'adminViewUserInfos' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              IDL.Text,
              IDL.Nat,
              IDL.Nat,
              IDL.Text,
              IDL.Text,
            )
          ),
        ],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkHasActiveSubscription' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'confirmExtendSubscription' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createFolder' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createPlan' : IDL.Func([Plan], [IDL.Bool], []),
    'deleteFile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteFolder' : IDL.Func([IDL.Nat], [], []),
    'deletePlan' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'downloadFile' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAllUsersWithSubscriptionStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExtensionDetails' : IDL.Func([IDL.Nat], [IDL.Text, IDL.Nat], ['query']),
    'getPaymentDestination' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPlan' : IDL.Func([IDL.Nat], [IDL.Opt(Plan)], ['query']),
    'getPurchaseDetails' : IDL.Func([IDL.Nat], [IDL.Text, IDL.Nat], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscribedUsers' : IDL.Func(
        [],
        [IDL.Vec(SubscribedUserEntry)],
        ['query'],
      ),
    'getSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'listFilesInFolder' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'listPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'listUserFolders' : IDL.Func([], [IDL.Vec(FolderRecord)], ['query']),
    'purchaseSubscription' : IDL.Func(
        [IDL.Nat],
        [IDL.Text, IDL.Nat],
        ['query'],
      ),
    'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'setPaymentDestination' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePlan' : IDL.Func([Plan], [IDL.Bool], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Nat), IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };