/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'contentType' : string,
  'ownerPrincipal' : Principal,
  'fileName' : string,
  'fileSize' : bigint,
  'fileId' : bigint,
  'folderId' : [] | [bigint],
  'uploadTime' : Time,
}
export interface FolderRecord {
  'ownerPrincipal' : Principal,
  'createTime' : Time,
  'folderName' : string,
  'folderId' : bigint,
}
export interface Plan {
  'active' : boolean,
  'planId' : bigint,
  'durationSeconds' : bigint,
  'priceE8s' : bigint,
  'storageLimitBytes' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscribedUserEntry {
  'startTime' : Time,
  'status' : SubscriptionStatus,
  'principal' : Principal,
  'endTime' : Time,
  'planId' : bigint,
  'storageLimitBytes' : bigint,
}
export interface Subscription {
  'startTime' : Time,
  'status' : SubscriptionStatus,
  'principal' : Principal,
  'usedStorageBytes' : bigint,
  'endTime' : Time,
  'planId' : bigint,
  'storageLimitBytes' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'revoked' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateSubscription' : ActorMethod<[bigint, bigint], undefined>,
  'adminDeleteFile' : ActorMethod<[bigint], boolean>,
  'adminDeleteUserFiles' : ActorMethod<[Principal], undefined>,
  'adminDeleteUserSubscription' : ActorMethod<[Principal], undefined>,
  'adminListUsers' : ActorMethod<[], Array<Subscription>>,
  'adminRevokeSubscription' : ActorMethod<[Principal], undefined>,
  'adminSetSubscription' : ActorMethod<
    [Principal, bigint, Time, Time, SubscriptionStatus],
    boolean
  >,
  'adminViewUserInfos' : ActorMethod<
    [],
    Array<[Principal, string, bigint, bigint, string, string]>
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkHasActiveSubscription' : ActorMethod<[Principal], boolean>,
  'confirmExtendSubscription' : ActorMethod<[bigint, bigint], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createFolder' : ActorMethod<[string], bigint>,
  'createPlan' : ActorMethod<[Plan], boolean>,
  'deleteFile' : ActorMethod<[bigint], boolean>,
  'deleteFolder' : ActorMethod<[bigint], undefined>,
  'deletePlan' : ActorMethod<[bigint], boolean>,
  'downloadFile' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getAllUsersWithSubscriptionStatus' : ActorMethod<
    [],
    Array<[Principal, string]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExtensionDetails' : ActorMethod<[bigint], [string, bigint]>,
  'getPaymentDestination' : ActorMethod<[], [] | [string]>,
  'getPlan' : ActorMethod<[bigint], [] | [Plan]>,
  'getPurchaseDetails' : ActorMethod<[bigint], [string, bigint]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscribedUsers' : ActorMethod<[], Array<SubscribedUserEntry>>,
  'getSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listFiles' : ActorMethod<[], Array<FileMetadata>>,
  'listFilesInFolder' : ActorMethod<[bigint], Array<FileMetadata>>,
  'listPlans' : ActorMethod<[], Array<Plan>>,
  'listUserFolders' : ActorMethod<[], Array<FolderRecord>>,
  'purchaseSubscription' : ActorMethod<[bigint], [string, bigint]>,
  'renameFolder' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPrincipal' : ActorMethod<[Principal], undefined>,
  'setPaymentDestination' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePlan' : ActorMethod<[Plan], boolean>,
  'uploadFile' : ActorMethod<
    [string, string, ExternalBlob, [] | [bigint], bigint],
    [] | [bigint]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];